"""Step 4.3: Step 4 report from the append-only results tables and experiment directories.

Writes reports/step4/experiment_summary.md, reports/step4/results/experiments.json and
figures (training curves, confusion matrices restricted to evaluated classes).
"""
from __future__ import annotations

import json
import shutil

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import sparse

from asl.config import PROJECT_ROOT, load_yaml

STEP4 = PROJECT_ROOT / "configs" / "step4_training.yaml"


def confusion_figure(npz, out, title, max_classes=60):
    cm = sparse.load_npz(npz).tocsr()
    support = np.asarray(cm.sum(1)).ravel()
    cls = np.flatnonzero(support)
    if len(cls) > max_classes:
        cls = cls[np.argsort(-support[cls], kind="stable")[:max_classes]]
    sub = cm[cls][:, cls].toarray()
    fig, ax = plt.subplots(figsize=(6, 5), dpi=120)
    im = ax.imshow(sub, cmap="Blues", interpolation="nearest")
    ax.set(xlabel="predicted class (subset)", ylabel="true class (subset)", title=title)
    fig.colorbar(im, ax=ax, fraction=0.046)
    fig.tight_layout()
    fig.savefig(out)
    plt.close(fig)
    return len(cls)


def main() -> None:
    c4 = load_yaml(STEP4)
    rep = PROJECT_ROOT / c4["output"]["reports_dir"]
    figs = rep / "figures"
    figs.mkdir(parents=True, exist_ok=True)
    exp_root = PROJECT_ROOT / c4["output"]["experiments_dir"]
    tables = {"benchmark/real": rep / "results" / "experiment_results.csv", "smoke/synthetic": rep / "smoke" / "smoke_results.csv"}
    records = []
    for kind, path in tables.items():
        if not path.exists():
            continue
        for r in pd.read_csv(path).to_dict("records"):
            d = exp_root / r["store"] / r["experiment_id"]
            meta = json.loads((d / "metadata.json").read_text())
            tag = f"{r['store']}__{r['experiment_id']}"
            if (d / "training_curves.png").exists():
                shutil.copy(d / "training_curves.png", figs / f"{tag}_curves.png")
            for split in ("val", "test", "train_fit"):
                if (d / f"confusion_{split}.npz").exists():
                    confusion_figure(d / f"confusion_{split}.npz", figs / f"{tag}_confusion_{split}.png",
                                     f"{r['experiment_id']} - {split}")
            records.append({"kind": kind, **r, "metadata": meta})
    (rep / "results").mkdir(exist_ok=True)
    (rep / "results" / "experiments.json").write_text(json.dumps(records, indent=2, default=str) + "\n")

    L = ["# Step 4 - experiment summary\n",
         "Generated by `scripts/s4_03_report.py` from the append-only tables "
         "`reports/step4/results/experiment_results.csv` (real data) and `reports/step4/smoke/smoke_results.csv` "
         "(synthetic smoke tests). Methodology: `docs/step4_methodology.md`.\n",
         "> **Status:** pipeline validation only. No experiment of the 18-run matrix has been run on data with "
         "validation/test videos. Smoke results are on SYNTHETIC data and mean nothing about ASL recognition.\n"]
    for kind in tables:
        rows = [r for r in records if r["kind"] == kind]
        if not rows:
            continue
        L += [f"## {kind}\n", "| store | experiment | train/val/test | train classes | epochs | best epoch | best val macro-F1 | "
              "test acc | test macro-F1 | test weighted-F1 | latency ms (b=1, mean / p95) | selection |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|"]
        f = lambda v: "–" if v is None or (isinstance(v, float) and np.isnan(v)) else (f"{v:.3f}" if isinstance(v, float) else v)
        for r in rows:
            L.append(f"| {r['store']} | {r['experiment_id']} | {r['train_samples']}/{r['validation_samples']}/{r['test_samples']} "
                     f"| {r['train_classes']} / {r['vocabulary_size']} | {f(r['epochs'])} | {f(r['best_epoch'])} | "
                     f"{f(r['best_val_macro_f1'])} | {f(r['test_accuracy'])} | {f(r['test_macro_f1'])} | {f(r['test_weighted_f1'])} "
                     f"| {r['mean_latency_ms']:.2f} / {r['p95_latency_ms']:.2f} ({r['latency_device']}) | {r['selection']} |")
        L.append("")
        for r in rows:
            m = r["metadata"]
            L += [f"### {r['store']} / {r['experiment_id']}\n",
                  f"- notes: {r['notes']}",
                  f"- environment: {m['environment']}; seed {m['seed']}; feature dim {m['feature_dim']}; "
                  f"parameters {m.get('params')}; batch size {m.get('batch_size_used', '–')}; train time "
                  f"{m['train_seconds']:.1f} s",
                  f"- evaluations: {m['evaluations']}",
                  "- latency: " + "; ".join(f"{x['timing']} b={x['batch_size']}: mean {x['mean_ms']:.2f} ms, median "
                                            f"{x['median_ms']:.2f}, p95 {x['p95_ms']:.2f}, {x['throughput_samples_per_s']:.0f} samples/s"
                                            for x in m["latency"]),
                  f"- resources: {m.get('resources', 'not recorded')}",
                  f"- artifacts: `experiments/{r['store']}/{r['experiment_id']}/`; figures: "
                  f"`reports/step4/figures/{r['store']}__{r['experiment_id']}_*.png`\n"]
    (rep / "experiment_summary.md").write_text("\n".join(L) + "\n")
    print(f"{len(records)} experiments summarized -> {rep / 'experiment_summary.md'}")


if __name__ == "__main__":
    main()
